-- CreateTable
CREATE TABLE "Bildirim" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "icerik" TEXT NOT NULL,
    "userId" INTEGER NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Bildirim_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
